const { VITE_CRYPTO_STORAGE_KEY, VITE_API_URL, VITE_ADMIN_NAME }
    = import.meta.env

const API_URL = VITE_API_URL
const ADMIN_NAME = VITE_ADMIN_NAME
const CRYPTO_STORAGE_KEY = VITE_CRYPTO_STORAGE_KEY

export { API_URL, ADMIN_NAME, CRYPTO_STORAGE_KEY }
